Added more comments to the run script.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+# Exit when any of the following command fails.
+set -e
+
+# Make sure the compiled eBPF program exists.
 [ -f minimal.o ] || { echo "File 'minimal.o' not found."; exit; }
 
 # Change mount namespace for current script.
@@ -11,21 +15,19 @@
 # on termination all children will be killed as well.
 [ /proc/$$/ns/pid -ef /proc/$PPID/ns/pid ] && exec unshare -fp $SHELL $0
 
-# From here on we work in a new mount namespace
-# Exit when any of the following command fails
-set -e
+# From here on we work in a new mount namespace.
 
 # We mount a new tmpfs for the ip command to store the namespaces into.
 # We made sure that the mount does not propagate to the parent namespace
 # due to the unshare command.
 # The namespace will be destroyed when the script ends, thus unmounting
-# and removing the created network namespace on /run/netns
+# and removing the created network namespace on /run/netns.
 mount -t tmpfs none /run/netns
 
 ip netns add h1
 ip netns add h2
 
-# Move the veth peers to different network namespaces
+# Move the veth peers to different network namespaces.
 ip link add h1-eth0 netns h1 type veth peer name h2-eth0 netns h2
 
 ip netns exec h1 ip addr add 10.0.0.1/24 dev h1-eth0
@@ -43,10 +45,12 @@ cat <<EOF
      h1                      h2
 EOF
 
+# Create the tc ingress hook and attach the eBPF program to it.
 echo
 ip netns exec h2 tc qdisc add dev h2-eth0 clsact
 ip netns exec h2 tc filter add dev h2-eth0 ingress bpf da obj minimal.o section classifier verbose
 
+# Print debug information in the background and run the ping command.
 echo
 tc exec bpf debug &
 ip netns exec h1 ping -4 10.0.0.2
